info:
  name: Create Book
  type: http
  seq: 5

http:
  method: POST
  url: http://127.0.0.1:8000/api/books
  body:
    type: json
    data: |-
      {
        "title": "Laravel入門",
        "author": "ルナ",
        "price": 3000
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
