info:
  name: Update Book
  type: http
  seq: 6

http:
  method: PUT
  url: http://127.0.0.1:8000/api/books/1
  body:
    type: json
    data: |-
      {
        "title": "Laravel入門（第2版）",
        "author": "ルナ",
        "price": 3500
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
